
# Pandas Final Assignment (Class 2 + Class 3)

### Topics Covered
- head()
- tail()
- info()
- shape
- dtypes
- loc
- iloc
- rename()
- set_index()
- reset_index()
- isnull()
- fillna()
- astype()
- replace()
- drop()
- duplicated()
- drop_duplicates()

### Instructions
- Use Pandas in every question.
- Write code in the blank code cell below each question.
- Print the required output.


# Q1. Display First Rows

## Problem Statement
Create the following DataFrame:

| Name | Age |
|------|-----|
| Aman | 21 |
| Rahul | 22 |
| Neha | 20 |
| Priya | 23 |
| Ravi | 24 |

Display the first 3 rows using `head()`.

## Sample Output
```python
First 3 rows of DataFrame
```

In [ ]:
# Write your code here
import pandas as pd

data = {
    "Name": ["Aman", "Rahul", "Neha", "Priya", "Ravi"],
    "Age": [21, 22, 20, 23, 24]
}

df = pd.DataFrame(data)

print(df.head(3))

    Name  Age
0   Aman   21
1  Rahul   22
2   Neha   20


# Q2. Display Last Rows

## Problem Statement
Create a DataFrame containing 6 student records.

Display the last 2 rows using `tail()`.

## Sample Output
```python
Last 2 rows of DataFrame
```

In [ ]:
# Write your code here
import pandas as pd

data = {
    "Name": ["Aman", "Rahul", "Neha", "Priya", "Ravi", "jojo"],
    "Age": [21, 22, 20, 23, 24, 25]
}

df = pd.DataFrame(data)

print(df.tail(2))

   Name  Age
4  Ravi   24
5  jojo   25


# Q3. Check DataFrame Information

## Problem Statement
Create a DataFrame containing:

```python
Name = ["Aman","Rahul","Neha"]
Marks = [80,75,90]
```

Display DataFrame information using `info()`.

## Sample Output
```python
<class 'pandas.core.frame.DataFrame'>
...
```

In [ ]:
# Write your code here
data = {
      "Name": ["Aman","Rahul","Neha"],
      "Marks": [80,75,90]
}
df = pd.DataFrame(data)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Marks   3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes


# Q4. Shape and Data Types

## Problem Statement
Create a DataFrame with:

```python
Name
Age
City
```

Print:
- Shape
- Data Types

## Sample Output
```python
(3,3)
object
int64
```

In [ ]:
# Write your code here
import pandas as pd
data = {
    "Name": ["Aman", "Rahul", "Neha", "Priya", "Ravi"],
    "Age": [21, 22, 20, 23, 24],
    "City": ["bpl","bpl","bpl","bpl","bpl"]
}
df =pd.DataFrame(data)

print(df.shape)
print(df.dtypes)

(5, 3)
Name    object
Age      int64
City    object
dtype: object
(5, 3)
Name    object
Age      int64
City    object
dtype: object


# Q5. Select Data using loc

## Problem Statement
Create a DataFrame with Name, Age and City.

Using `loc`, display the Name and City of the first row.

## Sample Output
```python
Name    Aman
City    Bhopal
```

In [ ]:
# Write your code here
import pandas as pd

data = {
    "Name": ["Aman", "Rahul", "Neha", "Priya", "Ravi"],
    "Age": [21, 22, 20, 23, 24],
    "City": ["bhopal", "bpl", "bpl", "bpl", "bpl"]
}

df = pd.DataFrame(data)
df.loc[:0,["Name","City"]]

   Name    City
0  Aman  bhopal


# Q6. Select Data using iloc

## Problem Statement
Create a DataFrame with at least 4 rows.

Using `iloc`, print:
- Second row
- First two columns

## Sample Output
```python
Selected row values
```

In [ ]:
# Write your code here

import pandas as pd

data = {
    "Name": ["Aman", "Rahul", "Neha", "Priya", "Ravi"],
    "Age": [21, 22, 20, 23, 24],
    "City": ["bpl", "bpl", "bpl", "bpl", "bpl"]
}

df = pd.DataFrame(data)
df.iloc[:1,0:2]

   Name  Age
0  Aman   21


# Q7. Rename a Column

## Problem Statement
Create a DataFrame:

```python
Name
Marks
```

Rename column `Marks` to `Score`.

## Sample Output
```python
Name  Score
```

In [5]:
# Write your code here

import pandas as pd

data = {
    "Name": ["Aman", "Rahul", "Neha", "Priya", "Ravi"],
    "Marks": [21, 22, 20, 23, 24],
    "City": ["bpl", "bpl", "bpl", "bpl", "bpl"]
}

df = pd.DataFrame(data)
df2 =df.rename(columns= {"Marks":"Score"})
df2

    Name  Score City
0   Aman     21  bpl
1  Rahul     22  bpl
2   Neha     20  bpl
3  Priya     23  bpl
4   Ravi     24  bpl


# Q8. Handle Missing Values

## Problem Statement
Create a DataFrame:

```python
Name = ["Aman", None, "Neha"]
Marks = [80, 75, None]
```

Fill missing values using `fillna()`.

## Sample Output
```python
Missing values replaced
```

In [7]:
# Write your code here
import pandas as pd
data = {
    "Name" : ["Aman", None, "Neha"],
    "Marks" : [80, 75, None]
}
df = pd.DataFrame(data)
df.fillna(0)

   Name  Marks
0  Aman   80.0
1     0   75.0
2  Neha    0.0


# Q9. Replace Values

## Problem Statement
Create a DataFrame:

```python
City = ["BPL", "IND", "BPL"]
```

Replace:
- BPL → Bhopal
- IND → Indore

## Sample Output
```python
Bhopal
Indore
Bhopal
```

In [15]:
# Write your code here

import pandas as pd

data = {
    "Name": ["Aman", "Rahul", "Neha", "Priya", "Ravi"],
    "Marks": [21, 22, 20, 23, 24],
    "City": ["bpl", "indr", "bpl", "bpl", "bpl"]
}

df = pd.DataFrame(data)
df["City"] = df["City"].replace("bpl", "Bhopal")
df["City"] = df["City"].replace("indr", "Indore")

print(df)

    Name  Marks    City
0   Aman     21  Bhopal
1  Rahul     22  Indore
2   Neha     20  Bhopal
3  Priya     23  Bhopal
4   Ravi     24  Bhopal


# Q10. Remove Duplicate Records

## Problem Statement
Create a DataFrame:

```python
Name = ["Aman","Rahul","Aman","Neha"]
```

Check duplicate rows using `duplicated()` and remove them using `drop_duplicates()`.

## Sample Output
```python
Aman
Rahul
Neha
```

In [17]:
# Write your code here
import pandas as pd

data = {
    "Name": ["Aman", "Rahul", "Aman", "Neha"]
}

df = pd.DataFrame(data)
print("Duplicate Rows:")
print(df.duplicated())
df2 = df.drop_duplicates()

print("\nAfter Removing Duplicates:")
print(df2)

Duplicate Rows:
0    False
1    False
2     True
3    False
dtype: bool

After Removing Duplicates:
    Name
0   Aman
1  Rahul
3   Neha