<a href="https://colab.research.google.com/github/pallvirajput06/Panadas_practice.py/blob/main/pandas_class4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 4: Data Selection & Filtering
Welcome to **Class 4** of our Pandas series. Today we’ll explore techniques to select and filter data in a DataFrame.

## 1. Boolean Indexing & Conditional Selection
- Use comparison operators to build conditions (e.g., `df['col'] > 50`).
- Pass the condition inside `df[...]` to get matching rows.
- Combine multiple conditions with `&` (AND), `|` (OR), and `~` (NOT).
- Parentheses are required when combining conditions.

In [ ]:
import pandas as pd
a = {
    "Name" : ["pallavi","jojo","janvi","kaplana"],
    "Age" : [20,21,22,23],
    "Score" : [80,93,77,99]
    }
b = pd.DataFrame(a)
b

      Name  Age  Score
0  pallavi   20     80
1     jojo   21     93
2    janvi   22     77
3  kaplana   23     99

In [ ]:
#1.selecting single column
b["Age"] > 22
#for only true values use this
b[b["Age"] > 22]


#2.selecting single column score > 85
b[b["Score"] > 85]

#3.multiple conditions (AND): Age > 27 AND score > 85
b[(b["Age"] > 27) & (b["Score"] > 85)]

#(OR OPERATOER)
b[(b["Age"] > 27) | (b["Score"] > 85)]

#5.NOT(~)
b[~(b['Score'] > 85)]

#6. age > 22 and score > 80
b[(b["Age"] > 22) & (b["Score"] > 80)]

      Name  Age  Score
3  kaplana   23     99

## 2. Filtering Rows with Multiple Conditions
- Combine two or more conditions to refine selection.
- Remember to enclose each condition in parentheses.

In [ ]:
#1. age > 25 and score > 85
b[(b["Age"] > 25) &(b["Score"] > 85)]
#2. age < 35 or score >= 90
b[(b['Age'] < 35) | (b['Score'] >= 90)]
#3. age between 25 and 35(inclusive)
b[(b['Age'] >= 25)  & (b["Score"] <= 35 )]

Empty DataFrame
Columns: [Name, Age, Score]
Index: []

## 3. Using `query()` for Cleaner Filtering
- `query()` allows filtering rows with a string expression.
- It's concise and readable for complex conditions.
- Variables can be passed using the `@` symbol.

In [ ]:
#1. simple Query : Age > 25
print(b.query("Age > 20"))

#2. multiple condition using query: Age < 35 and Score >= 85
print(b.query("Age < 35 and Score >= 85"))

#3.multiple conditions using query:Age >= 30 and Score >=90
b.query("Age >=20 and Score>=90")

#4.Threshold(@)
score = 90 #variable
b.query("Score >= @score")

      Name  Age  Score
1     jojo   21     93
2    janvi   22     77
3  kaplana   23     99
      Name  Age  Score
1     jojo   21     93
3  kaplana   23     99

      Name  Age  Score
1     jojo   21     93
3  kaplana   23     99

## 4. String Operations on Columns
- Use the `.str` accessor for vectorized string methods.
- Common methods: `contains`, `replace`, `startswith`, `endswith`, `lower`, `upper`.
- Useful for cleaning or filtering text data.

In [ ]:
print(b)

#1.convert name to lowercase().
print(b['Name'].str.lower())

#2.convert name to uppercase().
print(b['Name'].str.upper())

#3.Title() - > capatilized first letter of all the words.
print(b['Name'].str.title())

#4.Replace a substring ("oldstring") to ("newstring")
b["Name"].str.replace('jojo','jyotsana')

#5. check if name column contains the letter "a"
b[b['Name'].str.contains('a')]

#6.startswith('Letter') -> letter satrting with
b[b['Name'].str.startswith('p')]

#7.endswith('Letter') -> letter satrting with
b[b['Name'].str.endswith('i')]

      Name  Age  Score
0  pallavi   20     80
1     jojo   21     93
2    janvi   22     77
3  kaplana   23     99
0    pallavi
1       jojo
2      janvi
3    kaplana
Name: Name, dtype: object
0    PALLAVI
1       JOJO
2      JANVI
3    KAPLANA
Name: Name, dtype: object
0    Pallavi
1       Jojo
2      Janvi
3    Kaplana
Name: Name, dtype: object

      Name  Age  Score
0  pallavi   20     80
2    janvi   22     77

## Mini Practice
1. Build a DataFrame with columns such as Name, Age, City, Score.
2. Use boolean indexing to select rows where Age > 25.
3. Filter rows where City is either 'Delhi' or 'Mumbai'.
4. Use query() to find rows with Score >= 85 and Age < 35.
5. Clean a text column using str.replace or str.lower.

In [ ]:


# 1. Build a DataFrame with columns: Name, Age, City, Score


# 2. Use boolean indexing to select rows where Age > 25
# Write your code here

# 3. Filter rows where City is either 'Delhi' or 'Mumbai'
# Write your code here

# 4. Use query() to find rows with Score >= 85 and Age < 35
# Write your code here

# 5. Clean a text column using str.replace or str.lower
# Example: convert City names to lowercase or replace "delhi" with "New Delhi"
# Write your code here

---
## Summary
- Learned to use boolean indexing and conditional selection.
- Filtered rows with multiple conditions.
- Used `query()` for clean filtering.
- Applied string operations with the `.str` accessor.